### ISSUE TITLE
Getting value error after try to train model by running main.py in Licence_plate_recognition folder

### ISSUE THREAD

**Issue by chinya07** [GuiltyNeuron/ANPR#1]
@KhazriAchraf 
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by GuiltyNeuron** [comment]
@chinya07 could you please mention the whole error ( in wich line of code) and python version and the exple that you use (licence plate img)

**Comment by chinya07** [comment]
sorry its solved it was my mistake @KhazriAchraf

**Comment by chinya07** [comment]
I have one more query though, how can I get the image of that detected licence plate only after running object detection.py @KhazriAchraf

**Comment by GuiltyNeuron** [comment]
In /Licence_plate_detection/object_detection_yolo.py
line 100 : boxes.append([left, top, width, height])
you can use this vector [left, top, width, height] to make a crop in the input image

**Comment by chinya07** [comment]
yes I got it thank you @KhazriAchraf 
and can you tell me how this works on video input? I tried detection on input video(python object_detection.py --video=test.mp4) it captured frames and store the output file as test_yolo_out_py.avi format but it is not detecting the number plate though it was a simple video taken from directly front of a car number plate.
