### ISSUE TITLE
Low accuracy

### ISSUE THREAD

**Issue by centurions** [GuiltyNeuron/ANPR#12]
Hi 
Why the accuracy is very low with plates (tunisian) from this link ? (plate recognition)

https://drive.google.com/open?id=1CTLo2BYaThPiGkasMPY8lkJkinSe5Jez

**Comment by GuiltyNeuron** [comment]
Segmentation is not working well also we did not use a feature extraction approach while classifying the licence plate, this work needs a lot of improvement
