### ISSUE TITLE
Dataset for USA plate recognition

### ISSUE THREAD

**Issue by hsi1032** [GuiltyNeuron/ANPR#17]
Hi, Thank you for your great work

I wonder that how did you collect the digits of license plate recognition dataset in 
"ANPR/Licence_plate_recognition/USA_plates/"

And also, Are there digit images before binarizing the images
which means cropped digits in license plates?

**Comment by GuiltyNeuron** [comment]
Dataset is composed of caracters in different fonts, it's not cropped from a specefic place.
