### ISSUE TITLE
weights file information

### ISSUE THREAD

**Issue by madan0511** [GuiltyNeuron/ANPR#2]
Can you provide the trained yolo weights file?

**Comment by GuiltyNeuron** [comment]
Hi @madan0511 , here is a link to Kaggle where you can find Yolo weights, classes names and config file https://www.kaggle.com/achrafkhazri/licence-plate-detection-yolo-v3-trained-wights

**Comment by madan0511** [comment]
Hi, @KhazriAchraf thanks for replying,

mkp.pkl model file is also missing.
I want to train my own objects, how to train my own objects , should i use darknet architecture yolo 416 or 608 for training ?

**Comment by GuiltyNeuron** [comment]
Hi @madan0511 , here is a link about yolo training ( contains also all the stuff about this project ) 
https://towardsdatascience.com/automatic-license-plate-detection-recognition-using-deep-learning-624def07eaaf

and for the architecture, use what ever you want
