### ISSUE TITLE
Model weights file accuracy

### ISSUE THREAD

**Issue by madan0511** [GuiltyNeuron/ANPR#4]
The model file is overfitted, the model is not trained properly.

**Comment by GuiltyNeuron** [comment]
did you test it on Tunisian licence plate ??

**Comment by GuiltyNeuron** [comment]
This model is trained only on vehicle with tunisian plate so i guess it will work only on tunisian LP.

**Comment by madan0511** [comment]
No no, I'm mentioning about the detector which detects gate's grill with 99 % accuracy.

**Comment by GuiltyNeuron** [comment]
that's because all the LP looks the same, i am going to close this issue !!
