### ISSUE TITLE
cv2.error: OpenCV(4.1.1) /io/opencv/modules/dnn/src/darknet/darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: lapi.weights in function 'readNetFromDarknet'

### ISSUE THREAD

**Issue by ChipLubis97** [GuiltyNeuron/ANPR#6]
Hey KhazriAchraf, can you help me to solve this issue? Thank you

**Comment by nauyan** [comment]
@ChipLubis97 replace "lapi.weights" with the name of weights file that you are going to use for prediction or you can download weights from https://www.kaggle.com/achrafkhazri/licence-plate-detection-yolo-v3-trained-wights/downloads/licence-plate-detection-yolo-v3-trained-wights.zip/1 and use them.

**Comment by ChipLubis97** [comment]
It works. Thanks a lot bro

**Comment by SamarpanKumar** [comment]
l

> @ChipLubis97 replace "lapi.weights" with the name of weights file that you are going to use for prediction or you can download weights from https://www.kaggle.com/achrafkhazri/licence-plate-detection-yolo-v3-trained-wights/downloads/licence-plate-detection-yolo-v3-trained-wights.zip/1 and use them.

link is not working!!!
