### ISSUE TITLE
Morrocan LPR

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [GuiltyNeuron/ANPR#7]
Hey KhazriAchraf , i want to detect Morrocan plate it's like this :  file:///root/Desktop/marokko38.jpg how can i modify your code to detect the plate in real time ,

**Comment by ZIKO94ZIKO** [comment]
file:///root/Desktop/marokko38.jpg

**Comment by ZIKO94ZIKO** [comment]
http://licenseplatemania.com/fotos/marokko/marokko38.jpg

**Comment by GuiltyNeuron** [comment]
Detection : Train Yolo detector on your dataset ( images contains licences plates of Morrocan LP)
Recognition : 
- Use Tesseract
or
-  Connected component for the extraction of digits and build ur own digits dataset

**Comment by ZIKO94ZIKO** [comment]
thank u very much for sharing your code ^^

**Comment by zongoalbert** [comment]
HI @GuiltyNeuron  i have the same problem , i want to detect Moroccan  plate , please could you please give me an tutorial to flow to solve this problem : this is an example of Moroccan  plate   
![image](https://user-images.githubusercontent.com/55978810/71446976-a72b5a00-2729-11ea-8c61-86939ebec796.png)
Thanks in advance
