### ISSUE TITLE
Getting errors in main.py

### ISSUE THREAD

**Issue by biranchi2018** [GuiltyNeuron/ANPR#9]
I downloaded the dataset from kaggle 
https://www.kaggle.com/achrafkhazri/anpr-dataset-tunisian-plates-and-digits

I am getting errors after running 
$python3 main.py -mode train -d dataset

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    data, labels = load_dataset(args.d)
  File "/Users/biranchi/Desktop/Vettons License Plate Recognition/ANPR/Licence_plate_recognition/tools.py", line 209, in load_dataset
    gray = cv2.cvtColor(training_digit_image, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

**Comment by astha-singh-dev** [comment]
Same Issue is occurring with my file as well

**Comment by GuiltyNeuron** [comment]
Try python version 3.5.5 and opencv 4.1.1.26

**Comment by GuiltyNeuron** [comment]
the problem was from the image, it was graysclae and not RGB
